name: budget_mobile
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.6.0
  #linux: ^5.6.0
  #macos: ^5.6.0
  provider: ^6.0.5
  path_provider: ^2.1.1
  http: ^0.13.5
  intrinsic_grid_view: ^0.0.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  currency_formatter: ^2.2.2
  socket_io_client: ^3.1.1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  #flutter_qr_bar_scanner: ^3.0.2
  simple_radio_group: ^1.0.0
  dio: ^5.8.0+1
  file_picker: ^9.2.2
  open_filex: ^4.4.0
  flutter_cached_pdfview: ^0.4.3
  sqflite: ^2.4.2+1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/banners/
    - assets/icons/
    - assets/files/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansCode-VariableFont_wght.ttf
        - asset: assets/fonts/GoogleSansCode-Italic-VariableFont_wght.ttf
    - family: THSarabunNew
      fonts:
        - asset: assets/fonts/THSarabunNew/THSarabunNew.ttf
        - asset: assets/fonts/THSarabunNew/THSarabunNewBold.ttf
          weight: 700
        - asset: assets/fonts/THSarabunNew/THSarabunNewBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/THSarabunNew/THSarabunNewItalic.ttf
          style: italic
